//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Airple_Schedules = new HashSet<Airple_Schedules>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public string SeatData { get; set; }
    
        public virtual ICollection<Airple_Schedules> Airple_Schedules { get; set; }
    }
}
