//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public string Regnumber { get; set; }
        public string Ownername { get; set; }
        public int Ownerphone { get; set; }
        public string Owneremail { get; set; }
        public string Drivername { get; set; }
        public int Driverphone { get; set; }
        public string Isdoubledecker { get; set; }
        public string Category { get; set; }
        public string Coach { get; set; }
    }
}
