//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage_Trains
    {
        public int Id { get; set; }
        public int TrainId { get; set; }
        public int StationId { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual Train_Schedules Train_Schedules { get; set; }
        public virtual Train_Stations Train_Stations { get; set; }
        public virtual Train Train { get; set; }
    }
}
