//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETicketEntities : DbContext
    {
        public ETicketEntities()
            : base("name=ETicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Airplane> Airplanes { get; set; }
        public DbSet<Airple_Schedules> Airple_Schedules { get; set; }
        public DbSet<Bus> Buses { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Manage_Trains> Manage_Trains { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<Train_Compartments> Train_Compartments { get; set; }
        public DbSet<Train_Schedules> Train_Schedules { get; set; }
        public DbSet<Train_Stations> Train_Stations { get; set; }
        public DbSet<Train> Trains { get; set; }
    }
}
