//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string SeatType { get; set; }
        public Nullable<int> CompertmentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SeatId { get; set; }
    
        public virtual Airple_Schedules Airple_Schedules { get; set; }
        public virtual Train_Compartments Train_Compartments { get; set; }
    }
}
